use_small_heuristics = "Default"
fn_call_width = 80
struct_lit_width = 40
struct_variant_width = 40
single_line_if_else_max_width = 60

enum_discrim_align_threshold = 6
fn_args_layout = "Tall"
fn_single_line = true
format_strings = true
imports_layout = "HorizontalVertical"
#indent_style = "Visual"
imports_granularity = "Crate"
normalize_comments = true
struct_lit_single_line = true
use_try_shorthand = true
trailing_comma = "Vertical"
use_field_init_shorthand = true